require("config.keymaps.general")
require("config.keymaps.buffer")
require("config.keymaps.diagnostic")
require("config.keymaps.file")
require("config.keymaps.tab")
require("config.keymaps.window")
require("config.keymaps.terminal")
